// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/contact/submit.ts";
import * as $$$$$$0 from "./sections/Component.tsx";
import * as $$$$$$7 from "./sections/container/Container.tsx";
import * as $$$$$$1 from "./sections/Content/Breadcrumb.tsx";
import * as $$$$$$2 from "./sections/Content/Toast.tsx";
import * as $$$$$$3 from "./sections/Institutional/Policy.tsx";
import * as $$$$$$4 from "./sections/Institutional/Support.tsx";
import * as $$$$$$5 from "./sections/Institutional/WhereToBuy.tsx";
import * as $$$$$$8 from "./sections/mySection.tsx";
import * as $$$$$$6 from "./sections/Social/ContactForm.tsx";

const manifest = {
  "sections": {
    "elux-components-app/sections/Component.tsx": $$$$$$0,
    "elux-components-app/sections/container/Container.tsx": $$$$$$7,
    "elux-components-app/sections/Content/Breadcrumb.tsx": $$$$$$1,
    "elux-components-app/sections/Content/Toast.tsx": $$$$$$2,
    "elux-components-app/sections/Institutional/Policy.tsx": $$$$$$3,
    "elux-components-app/sections/Institutional/Support.tsx": $$$$$$4,
    "elux-components-app/sections/Institutional/WhereToBuy.tsx": $$$$$$5,
    "elux-components-app/sections/mySection.tsx": $$$$$$8,
    "elux-components-app/sections/Social/ContactForm.tsx": $$$$$$6,
  },
  "actions": {
    "elux-components-app/actions/contact/submit.ts": $$$$$$$$$0,
  },
  "name": "elux-components-app",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
